#!/bin/sh
# SPDX-FileCopyrightText: 2025 Rebel SQLite Library contributors
# SPDX-FileCopyrightText: 2022 Rebel Engine contributors
# SPDX-FileCopyrightText: 2017-2022 Godot Engine contributors
# SPDX-FileCopyrightText: 2015 Oksana Shadura
# SPDX-FileCopyrightText: 2011 David Martin
#
# SPDX-License-Identifier: BSD-2-Clause

# Git pre-commit hook that runs a clang-format style check.
# The `clang-format` rules are defined in `.clang-format` in the root directory.
# The version of `clang-format` used affects the output generated.
# To get consistent formatting, use the same clang-format version as the Github
# workflow style tests: currently version 18.
minimum_required_clang_format_version="16"
recommended_clang_format_version="18"

# Determine the major version of clang-format being used.
# Example output strings reported by `clang-format --version`:
# - Ubuntu: "Ubuntu clang-format version 11.0.0-2"
# - Fedora: "clang-format version 11.0.0 (Fedora 11.0.0-2.fc33)"
clang_format_version_string="$(clang-format --version | sed "s/[^0-9\.]*\([0-9\.]*\).*/\1/")"
clang_format_version="$(echo "$clang_format_version_string" | cut -d. -f1)"

if [ "$clang_format_version" -lt "$minimum_required_clang_format_version" ]; then
    echo "Error: Your version of clang-format is $clang_format_version_string."
    echo "The minimum required version of clang-format is $minimum_required_clang_format_version."
    echo "Please upgrade clang-format to ensure formatting is applied correctly."
    exit 1
fi

if [ "$clang_format_version" -lt "$recommended_clang_format_version" ]; then
    echo "Warning: Your version of clang-format is $clang_format_version_string."
    echo "The recommended version of clang-format is $recommended_clang_format_version."
    echo "Consider upgrading clang-format as formatting may not be applied correctly."
fi

if [ "$clang_format_version" -gt "$recommended_clang_format_version" ]; then
    echo "Warning: Your version of clang-format is $clang_format_version_string."
    echo "The maximum tested version of clang-format is $recommended_clang_format_version."
    echo "Consider downgrading clang-format as formatting may not be applied correctly."
fi

# The application and options.
application_name="clang-format"
options="--Wno-error=unknown"

# File extensions to parse.
include_extensions=".h .c .cpp"

# Directories and files to ignore.
# Exclude external code: submodules and third-party code.
exclude_directories="RebelSDK third-party"

# `pre-commit-style-check` uses six variables:
# `application_name`: The style check application to run.
# `options`: The options passed to the style check application.
# `include_files`: A list of specific filenames to be included.
# `include_extensions`: A list of filename extensions to be included.
# `exclude_directories`: A list of directories to be excluded.
# `exclude_file_patterns`: A list of file patterns to be exclued.
. "$(dirname -- "$0")/pre-commit-style-check"
